name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Angular to GitHub Pages
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          checkout: true
          path: dist/${{ github.event.repository.name }}/browser
          install_command: npm ci
          build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/
